SELECT * FROM FILMES;

UPDATE FILMES SET DURACAO = DURACAO + 20 WHERE ATORESPRINCIPAIS = 'Angelina Jolie';

UPDATE FILMES SET VALORINGRESSO = VALORINGRESSO * 0.9 WHERE GENERO = 'Action' AND ANO = 2011;

UPDATE FILMES SET TITULO = TITULO || '*' WHERE DURACAO <= 30;