@c:\temp\tipos_telefones.sql
commit;
@c:\temp\estados.sql
commit;
@c:\temp\cidades.sql
commit;
@c:\temp\usuarios.sql
commit;
@c:\temp\administradores.sql
commit;
@c:\temp\clientes.sql
commit;
@c:\temp\enderecos.sql
commit;
@c:\temp\clientes_enderecos.sql
commit;
@c:\temp\telefones.sql
commit;
@c:\temp\pedidos.sql
commit;
@c:\temp\autores.sql
commit;
@c:\temp\produtos.sql
commit;
@c:\temp\autores_produtos.sql
commit;
@c:\temp\pedidos_produtos.sql
commit;
