CREATE TABLE ESTADOS (
  uf VARCHAR(2),
  NOME VARCHAR(50),
  REGIAO VARCHAR(100)

);

CREATE TABLE CIDADE(
  COD_CIDADE INT PRIMARY KEY,
  NOME VARCHAR(50),
  UF VARCHAR (2)
);
  
DROP TABLE ALUNOS;

CREATE TABLE ALUNOS(
  nroMatricula VARCHAR(10) NOT NULL,
  cpf VARCHAR(20) NOT NULL,
  email VARCHAR(100) NOT NULL,
  nome VARCHAR(150) NOT NULL,
  anoIngresso NUMBER(4) NOT NULL,
  endereco VARCHAR(150) NULL,
  sexo CHAR(1) NOT NULL 
  
);

ALTER TABLE ALUNOS ADD CONSTRAINT PK_ALUNOS PRIMARY KEY (nroMatricula);
ALTER TABLE ALUNOS ADD CONSTRAINT AK1_ALUNOS UNIQUE (cpf);
ALTER TABLE ALUNOS ADD CONSTRAINT AK2_ALUNOS UNIQUE (email);

SELECT * FROM ALUNOS;